#ifndef PRAGMAS_ASYNCIO_PRAGMAS_H
#define PRAGMAS_ASYNCIO_PRAGMAS_H

/*
** Lattice 'C', Aztec 'C', SAS/C and DICE format pragma files.
**
** Original asyncio.library by Martin Taillefer
** Updates by Magnus Holmgren 1997
** Refactoring for Amiga NDK3.2 by amigazen project 2025
**
** Generated by LibDescConverter from an sfd file
*/

#ifndef CLIB_ASYNCIO_PROTOS_H
#include <clib/asyncio_protos.h>
#endif /* CLIB_ASYNCIO_PROTOS_H */

/* "asyncio.library" */
/*--- functions in V39.2 or higher --- */
#pragma libcall AsyncIOBase OpenAsync 1E 10803
#pragma libcall AsyncIOBase OpenAsyncFromFH 24 10803
#pragma libcall AsyncIOBase CloseAsync 2A 801
#pragma libcall AsyncIOBase SeekAsync 30 10803
#pragma libcall AsyncIOBase ReadAsync 36 09803
#pragma libcall AsyncIOBase WriteAsync 3C 09803
#pragma libcall AsyncIOBase ReadCharAsync 42 801
#pragma libcall AsyncIOBase WriteCharAsync 48 0802
#pragma libcall AsyncIOBase ReadLineAsync 4E 09803
#pragma libcall AsyncIOBase WriteLineAsync 54 9802
#pragma libcall AsyncIOBase FGetsAsync 5A 09803
#pragma libcall AsyncIOBase FGetsLenAsync 60 A09804
#pragma libcall AsyncIOBase PeekAsync 66 09803

#endif /* PRAGMAS_ASYNCIO_PRAGMAS_H */
