#ifndef CLIB_ASYNCIO_PROTOS_H
#define CLIB_ASYNCIO_PROTOS_H

/*
** 'C' prototypes. For use with 32 bit integers only.
**
** Original asyncio.library by Martin Taillefer
** Updates by Magnus Holmgren 1997
** Refactoring for Amiga NDK3.2 by amigazen project 2025
**
** Generated by LibDescConverter from an sfd file
*/

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef LIBRARIES_ASYNCIOH
#include <libraries/asyncio.h>
#endif
#ifndef DOS_DOS_H
#include <dos/dos.h>
#endif

/* "asyncio.library"*/
/*--- functions in V39.2 or higher ---*/
AsyncFile *OpenAsync(STRPTR fileName, ULONG mode, LONG bufferSize);
AsyncFile *OpenAsyncFromFH(BPTR handle, ULONG mode, LONG bufferSize);
LONG CloseAsync(AsyncFile *file);
LONG SeekAsync(AsyncFile *file, LONG position, LONG mode);
LONG ReadAsync(AsyncFile *file, APTR buffer, LONG bytes);
LONG WriteAsync(AsyncFile *file, APTR buffer, LONG bytes);
LONG ReadCharAsync(AsyncFile *file);
LONG WriteCharAsync(AsyncFile *file, ULONG ch);
LONG ReadLineAsync(AsyncFile *file, STRPTR buf, LONG bytes);
LONG WriteLineAsync(AsyncFile *file, STRPTR buf);
STRPTR FGetsAsync(AsyncFile *file, STRPTR buf, LONG bytes);
STRPTR FGetsLenAsync(AsyncFile *file, STRPTR buf, LONG bytes, LONG *length);
LONG PeekAsync(AsyncFile *file, APTR buffer, LONG bytes);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CLIB_ASYNCIO__PROTOS_H */
