#ifndef PROTO_ASYNCIO_H
#define PROTO_ASYNCIO_H

/*
** 'C' prototype and compiler specific header file combo
**
** Original asyncio.library by Martin Taillefer
** Updates by Magnus Holmgren 1997
** Refactoring for Amiga NDK3.2 by amigazen project 2025
**
** Generated by LibDescConverter from an sfd file
*/

#ifdef _NO_INLINE

#include <clib/asyncio_protos.h>

#else

#ifndef __NOLIBBASE__


#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif /* EXEC_LIBRARIES_H */

extern struct Library * AsyncIOBase;
#endif /* __NOLIBBASE__ */


#if defined(LATTICE) || defined(__SASC) || defined(_DCC)

#ifndef PRAGMAS_ASYNCIO_PRAGMAS_H
#include <pragmas/asyncio_pragmas.h>
#endif /* PRAGMAS_ASYNCIO_PRAGMAS_H */


#elif defined(AZTEC_C) || defined(__MAXON__) || defined(__STORM__)

#ifndef PRAGMA_ASYNCIO_LIB_H
#include <pragma/asyncio_lib.h>
#endif /* PRAGMA_ASYNCIO_LIB_H */

#elif defined(__VBCC__)

#include <clib/asyncio_protos.h>

#ifndef INLINE_ASYNCIO_PROTOS_H
#include <inline/asyncio_protos.h>
#endif /* INLINE_ASYNCIO_PROTOS_H */


#elif defined(__GNUC__)

#if defined(mc68000)
#ifndef INLINE_ASYNCIO_H
#include <inline/asyncio.h>
#endif /* INLINE_ASYNCIO_H */
#else
#include <clib/asyncio_protos.h>
#endif /* mc68000 */


/* Any other compiler */
#else

#include <clib/asyncio_protos.h>


#endif /* __GNUC__ */


#endif /* _NO_INLINE */

#endif /* PROTO_ASYNCIO__H */
